/**
 * Most items won't have a photo, and a wall of grey placeholders is hard to
 * scan visually. Guessing an emoji from the name gives every row a landmark.
 */
const RULES: Array<[RegExp, string]> = [
  [/\bmilk|dairy\b/i, "🥛"],
  [/cheese|cheddar|brie|mozzarella|parmesan|feta/i, "🧀"],
  [/butter|margarine|spread/i, "🧈"],
  [/yoghurt|yogurt|skyr/i, "🍶"],
  [/\begg/i, "🥚"],
  [/chicken|turkey|poultry/i, "🍗"],
  [/bacon|pork|ham|gammon/i, "🥓"],
  [/beef|steak|mince|lamb/i, "🥩"],
  [/fish|salmon|cod|tuna|haddock|prawn|scampi/i, "🐟"],
  [/sausage|hotdog|frankfurter/i, "🌭"],
  [/bread|loaf|sourdough|baguette|bagel|roll|bap|pitta|naan/i, "🍞"],
  [/croissant|pastry|danish/i, "🥐"],
  [/cereal|cornflake|granola|muesli|porridge|oat/i, "🥣"],
  [/pasta|penne|spaghetti|fusilli|macaroni|lasagne|tagliatelle/i, "🍝"],
  [/rice|risotto|basmati/i, "🍚"],
  [/noodle|ramen|udon/i, "🍜"],
  [/pizza/i, "🍕"],
  [/soup|broth|stock/i, "🥣"],
  [/bean|lentil|chickpea|pulse/i, "🫘"],
  [/tomato|passata|ketchup/i, "🍅"],
  [/potato|chips|fries|wedges/i, "🥔"],
  [/carrot/i, "🥕"],
  [/onion|shallot/i, "🧅"],
  [/garlic/i, "🧄"],
  [/pepper(?!corn)|capsicum|chilli|chili/i, "🌶️"],
  [/broccoli|spinach|kale|cabbage|greens|sprout|lettuce|salad|rocket/i, "🥬"],
  [/cucumber|courgette|zucchini/i, "🥒"],
  [/mushroom/i, "🍄"],
  [/corn|sweetcorn/i, "🌽"],
  [/pea\b|peas\b/i, "🫛"],
  [/avocado/i, "🥑"],
  [/apple|cider/i, "🍎"],
  [/banana/i, "🍌"],
  [/orange|satsuma|clementine|tangerine/i, "🍊"],
  [/lemon|lime/i, "🍋"],
  [/grape(?!fruit)/i, "🍇"],
  [/strawberr|raspberr|blueberr|berry|berries/i, "🍓"],
  [/melon|watermelon/i, "🍉"],
  [/peach|nectarine|apricot/i, "🍑"],
  [/pear/i, "🍐"],
  [/pineapple/i, "🍍"],
  [/mango/i, "🥭"],
  [/coconut/i, "🥥"],
  [/juice|smoothie/i, "🧃"],
  [/water|sparkling|still/i, "💧"],
  [/coffee|espresso|latte/i, "☕"],
  [/tea\b|teabag/i, "🍵"],
  [/beer|lager|ale|cider/i, "🍺"],
  [/wine|prosecco|champagne/i, "🍷"],
  [/cola|lemonade|fizzy|soda|tonic/i, "🥤"],
  [/chocolate|cocoa|nutella/i, "🍫"],
  [/biscuit|cookie|digestive/i, "🍪"],
  [/cake|muffin|brownie/i, "🍰"],
  [/ice cream|gelato|sorbet/i, "🍨"],
  [/crisps|popcorn|snack|nachos|tortilla/i, "🍿"],
  [/sweets|candy|haribo|gummy/i, "🍬"],
  [/honey/i, "🍯"],
  [/jam|marmalade|preserve/i, "🍓"],
  [/salt|sugar|flour|baking/i, "🧂"],
  [/oil|olive|vinegar/i, "🫒"],
  [/sauce|mayo|mustard|dressing|chutney/i, "🥫"],
  [/spice|herb|basil|oregano|cumin|paprika|cinnamon/i, "🌿"],
  [/nut|almond|cashew|peanut|walnut/i, "🥜"],
  [/tofu|tempeh|quorn|vegan/i, "🫛"],
  [/curry|tikka|masala/i, "🍛"],
  [/burger|patty/i, "🍔"],
  [/frozen|freezer/i, "🧊"],
  [/tin|can\b|tinned/i, "🥫"],
];

export function foodEmoji(name: string, brand?: string | null): string | null {
  const haystack = `${name} ${brand ?? ""}`;
  for (const [pattern, emoji] of RULES) {
    if (pattern.test(haystack)) return emoji;
  }
  return null;
}
